// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ittuorfjrmktmjwwmgad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dHVvcmZqcm1rdG1qd3dtZ2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzI5MDEsImV4cCI6MjA3MDA0ODkwMX0.QixJi_jj0rJ4Dg-1x-BzjoXuGBJCAmhgw330A4yCMZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});